//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RENTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosDeVehiculos
    {
        public int EventoID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public string TipoEvento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
    
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
