//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RENTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoID { get; set; }
        public Nullable<int> ReservaID { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> TipoPagoID { get; set; }
    
        public virtual Reservas Reservas { get; set; }
        public virtual TiposDePagos TiposDePagos { get; set; }
    }
}
