//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RENTA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.Contratos = new HashSet<Contratos>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int ReservaID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string EstadoReserva { get; set; }
        public Nullable<int> TarifaAplicada { get; set; }
        public Nullable<int> PromocionID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual Promociones Promociones { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
